project:
  type: website

website:
  title: EMT Children 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: web/emt-manuscript.qmd
        text: Manuscript
      - href: web/emt-children.qmd
        text: EMT results children
      - href: web/emt-adults.qmd
        text: EMT results adults
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true



