project:
  type: website

website:
  title: "nudz-emt-children"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: web/vr-emt.qmd
        text: VR-EMT
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true



