---
title: "VR EMT and RRBANS results for adults"
format: html
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE)
library(tidyverse)
library(gt)
library(papaja)
library(report)
here::i_am("web/emt-adults.qmd")
```

```{r data loading, results="hide"}
source(here::here("scripts/loading-adults.R"), encoding = "UTF-8")
```

## Sessions

All participants from the HCE group had the House as the second session. 

```{r session descriptives}
df_emt_adults %>%
  distinct(bindingid, Environment, Session) %>%
  count(Environment, Session)
```

## Participant descriptives

```{r participant descriptives, results="asis"}
df_single <- df_emt_adults %>%
  group_by(ID.x) %>%
  slice_head(n=1)
```

A total of `r n_distinct(df_single$ID.x)` participants were included in the study. The mean age was `r mean(df_single$Age.x)` years (SD = `r sd(df_single$Age.x)`).

```{r descriptives}
df_emt_adults %>%
  group_by(difficulty, error_type ) %>%
  select(errors) %>%
  report_table() %>%
  select(Group, Mean, SD, Median) %>%
  gt() %>%
    tab_header(title = "Descriptives of errors") %>%
    fmt_number(columns = vars(Mean, SD), decimals = 3) 
```

```{r descriptives plot}
ggplot(df_emt_adults, aes(errors, fill = Environment)) +
  geom_histogram(position = position_dodge(), binwidth = 0.1) +
  geom_density(alpha = 0.2) +
  facet_grid(rows = vars(error_type), cols = vars(difficulty), scales = "free_x")
```

```{r relative accuracy value}
ggplot(df_emt_adults, aes(difficulty, relative_correct)) +
  geom_jitter(width = 0.25, height = 0) +
  geom_violin(aes(group = difficulty, fill = difficulty), alpha = 0.2) +
  geom_smooth(method = "lm") +
  facet_grid(rows = vars(error_type), cols=vars(Environment), scales = "free_y")
```

## Correlation between performance and RBANS

:::{.callout-tip}
RBANS A.1 - seznam slov / word memory
RBANS A.2 - povídka / story memory
:::

```{r RBANS A 1 emt plots}
ggplot(df_emt_adults, aes(RBANS.A.1, relative_correct, color = Environment)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  ylim(0, 1) +
  facet_grid(col = vars(difficulty), rows = vars(error_type), scales = "free_y")  +
  labs(x = "RBANS A 1", 
       y = "Relative accuracy (1 is best)",
       title = "Correlation between RBANS 1 and EMT") +
  theme_apa() +
  theme(legend.position = "bottom", text = element_text(size=20))
```

```{r RBANS A 2 emt plots}
ggplot(df_emt_adults, aes(RBANS.A.2, relative_correct, color = Environment)) +
  geom_point() +
  ylim(0, 1) +
  geom_smooth(method = "lm") +
  facet_grid(col = vars(difficulty), rows = vars(error_type), scales = "free_y")  +
  labs(x = "RBANS A 2",
       y = "Relative accuracy (1 is best)",
       title = "Correlation between RBANS 2 and Relative accuracy in EMT separated by difficulty") +
  theme_apa() +
  theme(legend.position = "bottom", text = element_text(size=20))
```

```{r RBANS A 1 emt correlation}
ggplot(df_emt_adults, aes(RBANS.A.1, relative_correct, color = Environment)) +
  geom_point() +
  ylim(0, 1) +
  geom_smooth(method = "lm") +
  facet_wrap(~error_type, scales = "free_y")  +
  labs(x = "RBANS A 2",
       y = "Relative accuracy (1 is best)",
       title = "Correlation between RBANS 1 and Relative accuracy in EMT for all difficulties") +
  theme_apa() +
  theme(legend.position = "bottom", text = element_text(size=20))
```

```{r RBANS A 2 emt correlation}
ggplot(df_emt_adults, aes(RBANS.A.2, relative_correct, color = Environment)) +
  geom_point() +
  ylim(0, 1) +
  geom_smooth(method = "lm") +
  facet_wrap(~error_type, scales = "free_y")  +
  labs(x = "RBANS A 2",
       y = "Relative accuracy value",
       title = "Correlation between RBANS 2 and Relative accuracy in EMT for all difficulties") +
  theme_apa() +
  theme(legend.position = "bottom", text = element_text(size=20))
```

```{r}
df_emt_adults %>%
  #filter(Environment == "House") %>%
  pivot_longer(c(RBANS.A.1, RBANS.A.2), names_to = "RBANS", 
               values_to = "RBANS_value") %>%
  group_by(Environment, error_type, RBANS) %>%
  group_modify(~broom::tidy(cor.test(.$RBANS_value, .$relative_correct, method = "spearman"))) %>%
  summarise(result = str_glue("r = {round(estimate, 3)} (p = {apa_p(p.value)})")) %>%
  pivot_wider(names_from = RBANS, values_from = result) %>%
  ungroup() %>%
  gt() %>%
  tab_header(title = "Correlation between RBANS and EMT for house environment for all difficulties",
             subtitle = "Spearman's rho, not corrected for multiple comparisons")
```


```{r}
df_emt_adults %>%
  filter(error_type == "incorrect_placement") %>%
  group_by(difficulty) %>%
    group_modify(~broom::tidy(t.test(.$errors ~ .$Environment))) %>%
    ungroup() %>%
    select(difficulty, estimate, p.value) %>%
    gt() %>%
    tab_header(title = "T-test for incorrect placement errors between environments",
             subtitle = "Not corrected for multiple comparisons")
```